# A sample TOML config file.

[dbchbuild]
h="localhost:27017"
d="chbuild"
u="tmplbuild"
p="@tmpbu.sex"
[config]
builderid="594f665df54c58a2udfl54d3er"

dev="false"
builderwait=2
nob=4
minify="http://localhost:8000/min"
minifycompress="http://localhost:8000/mincom"
compress="http://localhost:8000/com"
minifyKey="minlocXYU5@#."
webpath="/Users/d/workspace/html/htdocs"
zipfileextallow=".ico,.jpg,.jpeg,.png,.gif,.txt,.html,.js,.css,.eot,.svg,.ttf,.woff,.woff2,.otf"
templatepath="../bportal/templates"